[workspace]
authors = ["jgsimard <jeangab23@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "bajo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install_prek = "prek install"
test = { cmd = "bash run_tests.sh", depends-on = [] }
bench_quat = "mojo -I. bench/bench_quat.mojo"
bench_aabb = "mojo -I. bench/bench_aabb.mojo"

[dependencies]
mojo = ">=0.26.2.0.dev2026030305,<0.27"
max = ">=26.2.0.dev2026030305,<27"
python = ">=3.14.3,<3.15"
suitesparsegetpy = ">=0.1.1,<0.2"

[pypi-dependencies]
dearpygui = ">=2.2, <3"
