[[repos]]
repo = "local"
hooks = [
    { id = "mojo-format", name = "Mojo Format", entry = "pixi run mojo format .", language = "system", pass_filenames = false, always_run = true },
    { id = "mojo-host-tests", name = "Mojo Host Tests", entry = "pixi run test_host", language = "system", pass_filenames = false, always_run = true }
]
